version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017" 
    volumes:
      - mongo_db:/data/db

  demo-api:
    build: .
    ports:
      - 3000:3000
    env_file: "docker.env"
    depends_on:
      - mongo_db
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: restart
          path: package.json
    
volumes:
  mongo_db: {}